services:
  - type: web
    name: travel-planner-api
    env: node
    plan: free
    buildCommand: NODE_OPTIONS="--max-old-space-size=460" npm install && NODE_OPTIONS="--max-old-space-size=460" npm run build:tsc
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
