services:
  - type: web
    name: travel-planner-api
    env: node
    plan: free
    buildCommand: bash build.sh
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
